spring:
  application:
    name: springvibe

  # ==========================
  # Database Configuration (MySQL)
  # ==========================
  datasource:
    url: jdbc:mysql://localhost:3306/springvibe?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    generate-ddl: true

# ==========================
# Logging Configuration
# ==========================
logging:
  level:
    org.springframework.jdbc: DEBUG


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method       # sorts by GET/POST/PATCH/DELETE
    tags-sorter: alpha              # sorts controllers alphabetically
    try-it-out-enabled: true        # enables Try it out by default
    #or alpha->alphabetically, method-> method wise
  # Explicitly permit these paths — important once security filter is active
  paths-to-match: /api/**